## Script to create an RDS file that contains:
#
# - Rows: all BirdNET detections processed between April 2025 and July 2025
#         (with 2 seconds of overlap and a sensitivity of 1.5)
# - Columns: audio file name, detection begin time, detection end time,
#            species name (in English), and species score.
#-------------------------------------------------------------------------------
library(data.table)
library(tidyverse)

# List all .txt files generated by BirdNET
# F2010 = Files from 2010
F10 <- list.files(path="OriginalData/BirdNETOutput/2010", recursive = TRUE, pattern="\\.txt$", full.names = TRUE)
# 2011
F11 <- list.files(path="OriginalData/BirdNETOutput/2011", recursive = TRUE, pattern="\\.txt$", full.names = TRUE)
# 2012
F12 <- list.files(path="OriginalData/BirdNETOutput/2012", recursive = TRUE, pattern="\\.txt$", full.names = TRUE)
# 2013
F13 <- list.files(path="OriginalData/BirdNETOutput/2013", recursive = TRUE, pattern="\\.txt$", full.names = TRUE)
# 2014
F14 <- list.files(path="OriginalData/BirdNETOutput/2014", recursive = TRUE, pattern="\\.txt$", full.names = TRUE)

# Combine all file paths into one list
FilesBirdNET <- c(F10,F11,F12,F13,F14)

# Read all BirdNET .txt files to extract species occurrences
BirdNETData <- rbindlist(sapply(FilesBirdNET, fread, simplify = FALSE, drop=c(1:3,6:8)),
                         use.names = TRUE, idcol = "FileName")

# Clean up the audio file names
BirdNETData$FileName <- basename(BirdNETData$FileName) %>%
  gsub("\\.BirdNET\\.selection\\.table\\.txt$", "", .)

# Save the object as an RDS file
saveRDS(object=BNout, file="CleanedData/BNetProcOutput.rds")
