## Script for preparation of Amazon birds vocalization data

## Receives detection raw data and returns:

## NDETSG: 3D table (site groups X dates X species) with number of detections by group of
##    sites, date and species (one detection corresponds to a recording segment
##    where the BirdNet score for the species is above the user-defined treshold);

## DATSG: 2D table (dates X site groups) with dates corresponding to the surveys 
##    of each group of sites in each year;

## EFFGmins: 2D table (site groups X dates) with effort (minutes of recording) for each group
##    of sites and days of each year;

## EFFGsits: 2D table (site groups X dates) with effort (number of sites per group) for each
##    group of sites and days of each year;

# ------------------------------------------------------------------------------
## Clean work space:
rm(list=ls())
## Libraries
library(tictoc)
## Load data:
# Now we can load the input files:

# "BNDetYearSpotGroupFile" is an RDS file that contains the following objects:
#   - BNoutClean: A cleaned version of the output generated by BirdNET. 
#   - Dates: A list indicating the corresponding date (YY-DD-MM) to each detection in 'BNoutClean'.
#   - Spot: A list indicating the location (spot name) for each detection in 'BNoutClean'.
#   - groups: A list assigning each spot to a corresponding group.
#   - vafi: A data frame containing information about all valid audio files.
#           It has three columns: file name, group, and duration for each file.
BNrds <- readRDS("CleanedData/BNDetDatesSpotGroupFile.rds")

# "SITES" is a CSV file whose dimensions are:
# - Rows: sites
# - Columns: ID data of each site (name, forest type (old growth = 0, secondary
#             forest = 1), geographic coordinates (X and Y))
SITES <- read.csv("OriginalData/locations_diurnal.txt", head=TRUE, sep="\t")

# ------------------------------------------------------------------------------
# 1. Load and organize data

# 1.1 Load detection data and supporting datasets
BNout <- BNrds$BNoutClean  # All BN detections. Columns: 'FileName', 'Begin Time (s)', 
# 'Common Name', and 'Confidence'
BNSpot <- as.character(BNrds$Spot)  # Spot names from all BN detections
BNvafi <- BNrds$vafi  # Data frame with all valid audio files. Columns: 'file_name', 
# 'group', 'site', 'date', and 'duration_min'

# 1.2 Filter detections based on a confidence threshold
# Set the threshold to filter detection probabilities indicating presence of vocalizations
thr <- 0.9
# thr <- 0.85
# thr <- 0.99

# Keep only detections above the confidence threshold
keep <- BNout$Confidence > thr
BNout <- BNout[keep, ]
BNSpot <- BNSpot[keep]
BNDates <- BNrds$Dates[keep]
rm(keep)
# Clean out rows with NA in all cols but filename
chuck <- which(is.na(BNout$`Common Name`))
BNout <- BNout[-chuck,]
BNSpot <- BNSpot[-chuck]
BNDates <- BNDates[-chuck]

# 1.3 Extract unique species names and count them
source("Functions/NameFix.R")
spsnames <- unique(na.omit(BNout$`Common Name`)) # Unique species names
nsps <- length(spsnames) # Number of unique species names

# # 1.4 Match species names to official SACC list
sacc <- read.csv("OriginalData/SACCList2025.csv", sep = ",", h=T)
# Identify species names not found in SACC list
ifix <- which(!spsnames %in% sacc$English.name)
for(i in ifix) {
  spsnames[i] <- name_fix(spsnames[i])
}
# Sort spsnames according to the SACC list order
spsnames <- spsnames[order(match(spsnames, sacc$English.name))]
# Check if all sps names in BNout appear in spsnames and fix if not
if(any(!unique(BNout$`Common Name`) %in% spsnames)) {
  needfix <- unique(BNout$`Common Name`)[which(!unique(BNout$`Common Name`) %in% spsnames)]
  for(i in 1:length(needfix)){
    oldname <- needfix[i]
    newname <- name_fix(needfix[i])
    BNout$`Common Name`[which(BNout$`Common Name`==oldname)]<- newname
  }
}

# Update spsnames with the scientific names
spsnames <- unname(setNames(sacc$Scientific.name, sacc$English.name)[spsnames])


# 1.5 Create 'shortSITES' object with coordinates of surveyed sites.
# Filter 'SITES' to keep only those presents in 'BNSpot'.
shortSITES <- SITES[which(SITES$Spot %in% BNSpot), ]

# 1.6 Load 'groups' object
# Vector of site groups based on dendrogram clustering
# groups <- cutree(dendrog, h = dmin)
groups <- BNrds$groups

# ------------------------------------------------------------------------------
## 2 Define output dimensions:

# Sites names list:
sitel <- sort(unique(BNSpot))
# Number of sites:
nsites <- length(unique(sitel))
# Number of sites groups:
ngroups <- length(names(groups))
# Vector of vectors of groups where each vector of groups has all sites
# belonging to that group:
sitegroup <- groups
# Groups names list (the name of each groups is the name of the first site
# belonging to that group):
groupl <- names(groups)
# Years list:
yearl <- as.numeric(unique(substr(BNvafi$date,1,4)))
# Obtain the maximum number of surveying days in each year based on groups:
vafiyr <- as.numeric(substr(BNvafi$date,1,4))
maxdy<-rep(NA,length(yearl))
for(i in 1:length(yearl)){
  cyr <- yearl[i]
  cvafi <- unique(BNvafi[,c(2,4)][which(vafiyr==cyr),])
  maxdy[i] <- max(rowSums(table(cvafi$group,cvafi$date)))
}


# ------------------------------------------------------------------------------
## 3 Define output tables:

# Table 1 - number of detections by group, day and species:
NDETSG <- array(data=NA,dim=c(ngroups,sum(maxdy),nsps))
dimnames(NDETSG)[[3]] <- spsnames

# Dates of the surveying days by site over the years:
DATSG <- t(matrix(data=NA,nrow=ngroups,ncol=sum(maxdy)))
DATSG <- data.frame(DATSG)
for(i in 1:ngroups) {class(DATSG[,i])="Date"}

# Effort (minutes of recording) by day and group:
EFFGmins <- matrix(data=NA,nrow=ngroups,ncol=sum(maxdy))

# Effort (number of surveyed sites) by day and group:
EFFGsits <- matrix(data=NA,nrow=ngroups,ncol=sum(maxdy))

# ------------------------------------------------------------------------------

## Fill output tables:
tic()
for(i in 1:nsps) {                  # loop through species
  cat("especie =",i,"\n")
  # get column corresponding to current species
  
  # define current year
  for(j in 1:length(yearl)) {
    cat("ano =",j,"\n")
    cy <- yearl[j] # "cy" = "current year"
    
    # define current group
    for(k in 1:ngroups) {
      cat("\nespecie = ", i, "\nano = ", j, "\ngrupo =",k,"\n", "\n-------------")
      cgn <- names(sitegroup[k]) # cgn for current group name"
      cg <- sitegroup[[k]]       # cg for current group
      
      # get dates belonging to current group and year:			
      cdg <- sort(unique(BNvafi$date[which((BNvafi$group==cgn) & (substr(BNvafi$date,1,4)==cy))])) # "cdg" = "current day group"
      
      # skip to the next group if there are no surveyed days in "cy":
      if(length(cdg)==0) next
      
      # Obtain "fdc" (first day column), which is the first column to be filled
      # (related to the first day from current year)
      if(j==1) { fdc <- 1 } else { fdc<-sum(maxdy[1:(j-1)])+1 }
      
      # # Fill DATSG and effort tables (EFFGmins, EFFGsits)
      if (i == 1) {
        # Save the dates at "DATSG":
        DATSG[fdc:(fdc+length(cdg)-1),k] <- cdg
        
        # Save effort (minutes) and number of sites for each sampling day
        for(l in 1:length(cdg)) {
          cd <- cdg[l]
          # Save effort in minutes of recording at "EFFGmins":
          EFFGmins[k, fdc+l-1] <- sum(BNvafi$duration_min[BNvafi$group == cgn & BNvafi$date == cd])
          
          # Save effort in number of sites at "EFFGsits":
          EFFGsits[k, fdc+l-1] <- length(unique(BNvafi$site[BNvafi$group == cgn & BNvafi$date == cd]))
        }
      }
      # Counting detections per day for each species and group, fill it on NDETSG
      for(l in 1:length(cdg)) {
        cd <- cdg[l] # current day
        ndet <- sum(BNDates==cd & BNSpot%in%cg & BNout$`Common Name` == spsnames[i], na.rm = TRUE)
        NDETSG[k, fdc+l-1, i] <- ndet
      } # l dates
    } # k sites
  } # j years	
} # i species
toc()

# ------------------------------------------------------------------------------
## Save output

# Clean workspace:
list=ls()
list <- list[-which(list%in%c("DATSG","EFFGmins","EFFGsits","shortSITES","groups","NDETSG"))]
rm(list=list, list)

# Save separatedely the CSV file "groups" to be used in the Python script:
# write.table(groups, "C:/Users/ecopo/OneDrive/NSpsOccDynManaus/Data Processing/Data/groups.csv", sep = "\t", row.names=FALSE, quote=TRUE)

# Save output as an "RData" file:
save.image("DataObjects/DataArrays_R.RData")